CREATE TABLESPACE firstDB
DATAFILE 'C:/oraclexe/data/first.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

CREATE USER user1 IDENTIFIED BY 12341234
DEFAULT TABLESPACE firstDB;

ALTER USER user1 DEFAULT TABLESPACE firstDB;

GRANT CREATE SESSION TO user1;
GRANT CREATE TABLE TO user1;
GRANT UNLIMITED TABLESPACE TO user1;
GRANT DBA To user1;
